"""Structured memo JSON builder.

Assembles the API-facing memo from pipeline branch results. Contains no LLM
calls: the recommendation is generated by agents.report and passed in, and
explainability parsing happens in agents.explainability.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any

_OUTPUT_SANITY_PREFIX = "output sanity check:"
_INPUT_CLAIM_PREFIX = "assumption, not validated:"

_CITATION_RE = re.compile(
    r"^\[(?P<id>[^\]]+)\]\s*(?P<claim>.+?)\s*\(source:\s*(?P<source>.+)\)$"
)
_REF_RE = re.compile(r"\(ref:\s*([^)]+)\)")


def build_memo_json(
    *,
    category_key: str,
    company: dict[str, Any],
    plan: dict[str, Any],
    branch_plan: dict[str, Any],
    branch_results: list[dict[str, Any]],
    full_retrievals: list[dict[str, Any]] | None = None,
    recommendation: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build JSON-serializable memo payload preserving all memo sections."""
    company_name = company.get("company_name", "Company")
    project = company.get("proposed_project", {})
    project_name = project.get("name", "AI Project")
    category = company.get("project_category", "AI")
    branch_field = branch_plan.get("branch_field", "architecture")
    branch_labels = [
        b.get("label", f"Option {i + 1}")
        for i, b in enumerate(branch_plan.get("branches", [])[:2])
    ]

    branches_json: list[dict[str, Any]] = []
    labels = ["Scenario A", "Scenario B"]

    for i, result in enumerate(branch_results[:2]):
        branch_info = result.get("branch") or {}
        modeling = result.get("modeling") or {}
        retrieval_summary = result.get("retrieval") or {}
        full_retrieval = (
            (full_retrievals[i] if full_retrievals and i < len(full_retrievals) else None)
            or retrieval_summary
        )
        parsed = result.get("explanation_parsed") or {}

        branch_value = branch_info.get(branch_field) or modeling.get("branch_value") or "?"

        scenarios = modeling.get("scenarios") or {}
        lik = scenarios.get("likely", {})
        flags_raw = modeling.get("flagged_assumptions") or retrieval_summary.get(
            "flagged_assumptions", []
        )

        branches_json.append(
            {
                "label": labels[i],
                "branch_id": branch_info.get("branch_id"),
                "branch_label": branch_info.get("label"),
                "branch_field": branch_field,
                "branch_value": branch_value,
                "metrics": _metrics_table(scenarios),
                "cost_breakdown_likely": lik.get("cost_breakdown") or {},
                "flagged_assumptions": [_parse_flag(f) for f in flags_raw],
                "citations": _parse_citations(retrieval_summary.get("citations") or []),
                "explainability": {
                    "text": parsed.get("text") or result.get("explanation") or "",
                    "overall_confidence": parsed.get("overall_confidence"),
                    "dimensions": parsed.get("dimensions") or [],
                },
                "retrieval": {
                    "reconciled_inputs": retrieval_summary.get("reconciled_inputs")
                    or full_retrieval.get("reconciled_inputs"),
                    "verdicts": _extract_verdicts(full_retrieval),
                },
            }
        )

    return {
        "meta": {
            "category_key": category_key,
            "project_category": category,
            "company_id": company.get("company_id"),
            "company_name": company_name,
            "project_name": project_name,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
        "decision_framing": {
            "company_name": company_name,
            "project_name": project_name,
            "project_description": company.get("project_description", ""),
            "branch_field": branch_field,
            "branch_labels": branch_labels,
            "summary": (
                f"{company_name} is evaluating {project_name}: "
                f"{company.get('project_description', '')} "
                f"The {branch_field.replace('_', ' ')} has not been finalized."
            ),
        },
        "plan": plan,
        "branch_plan": branch_plan,
        "branches": branches_json,
        "recommendation": recommendation
        or {"winner": None, "reasoning": "", "confidence_caveat": "", "text": ""},
    }


def _metrics_table(scenarios: dict[str, dict[str, Any]]) -> dict[str, Any]:
    con = scenarios.get("conservative", {})
    lik = scenarios.get("likely", {})
    opt = scenarios.get("optimistic", {})

    rows: dict[str, dict[str, Any]] = {
        "roi_3yr": {
            "conservative": con.get("roi"),
            "likely": lik.get("roi"),
            "optimistic": opt.get("roi"),
        },
        "payback_months": {
            "conservative": con.get("payback_months"),
            "likely": lik.get("payback_months"),
            "optimistic": opt.get("payback_months"),
        },
        "annual_value_usd": {
            "conservative": con.get("annual_value_usd"),
            "likely": lik.get("annual_value_usd"),
            "optimistic": opt.get("annual_value_usd"),
        },
        "total_cost_3y_usd": {
            "conservative": con.get("total_cost_3y_usd"),
            "likely": lik.get("total_cost_3y_usd"),
            "optimistic": opt.get("total_cost_3y_usd"),
        },
    }

    if con.get("tickets_deflected_annual") is not None:
        rows["tickets_deflected_annual"] = {
            "conservative": con.get("tickets_deflected_annual"),
            "likely": lik.get("tickets_deflected_annual"),
            "optimistic": opt.get("tickets_deflected_annual"),
        }
    elif con.get("additional_conversions_annual") is not None:
        rows["additional_conversions_annual"] = {
            "conservative": con.get("additional_conversions_annual"),
            "likely": lik.get("additional_conversions_annual"),
            "optimistic": opt.get("additional_conversions_annual"),
        }
    elif con.get("maintenance_savings_annual") is not None:
        rows["maintenance_savings_annual"] = {
            "conservative": con.get("maintenance_savings_annual"),
            "likely": lik.get("maintenance_savings_annual"),
            "optimistic": opt.get("maintenance_savings_annual"),
        }
        rows["avoided_downtime_value_annual"] = {
            "conservative": con.get("avoided_downtime_value_annual"),
            "likely": lik.get("avoided_downtime_value_annual"),
            "optimistic": opt.get("avoided_downtime_value_annual"),
        }

    return rows


def _parse_flag(text: str) -> dict[str, Any]:
    flag_type = "input_claim"
    lower = text.lower()
    if _OUTPUT_SANITY_PREFIX in lower:
        flag_type = "output_sanity_check"
    elif "user unknown; branch" in lower:
        flag_type = "branch_unknown"

    ref_match = _REF_RE.search(text)
    cited_fact_id = ref_match.group(1).strip() if ref_match else None

    # Strip standard prefix for display
    display = text
    if display.startswith(_INPUT_CLAIM_PREFIX):
        display = display[len(_INPUT_CLAIM_PREFIX) :].strip()

    return {
        "text": display,
        "raw": text,
        "type": flag_type,
        "cited_fact_id": cited_fact_id,
    }


def _parse_citations(citations: list[str]) -> list[dict[str, str]]:
    parsed: list[dict[str, str]] = []
    for c in citations:
        m = _CITATION_RE.match(c.strip())
        if m:
            parsed.append(
                {
                    "fact_id": m.group("id"),
                    "claim": m.group("claim").strip(),
                    "source": m.group("source").strip(),
                }
            )
        else:
            parsed.append({"fact_id": "", "claim": c, "source": ""})
    return parsed


def _extract_verdicts(retrieval: dict[str, Any]) -> list[dict[str, Any]]:
    for turn in retrieval.get("transcript") or []:
        if turn.get("speaker") == "benchmark_retrieval":
            return turn.get("verdicts") or []
    return []
